server:
    port: 8080
    servlet:
        context-path: /wechat

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wechat?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

        #url: jdbc:mysql://120.55.40.94/wechat?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        #username: root
        #password: QWER1234asdf

mybatis:
  type-aliases-package: com.demo.wechat.domain.model
  mapper-locations: classpath:mapping/*.xml

